// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pb_schemas/inventory/v1/stock.proto

package inventoryv1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common error types
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`             // e.g., "sku", "quantity"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // e.g., "SKU cannot be empty"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InventoryError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // e.g., "INVALID_SKU"
	Details       []*ErrorDetail         `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"` // Field-specific errors
	Status        *status.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // Standard status info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryError) Reset() {
	*x = InventoryError{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryError) ProtoMessage() {}

func (x *InventoryError) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryError.ProtoReflect.Descriptor instead.
func (*InventoryError) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InventoryError) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *InventoryError) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// Data messages (unchanged from your original)
type SKUInventory struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sku             string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	CurrentStock    float64                `protobuf:"fixed64,2,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	ReservedStock   float64                `protobuf:"fixed64,3,opt,name=reserved_stock,json=reservedStock,proto3" json:"reserved_stock,omitempty"`
	MinStockLevel   float64                `protobuf:"fixed64,4,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`
	MaxStockLevel   float64                `protobuf:"fixed64,5,opt,name=max_stock_level,json=maxStockLevel,proto3" json:"max_stock_level,omitempty"`
	LastStockUpdate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_stock_update,json=lastStockUpdate,proto3" json:"last_stock_update,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SKUInventory) Reset() {
	*x = SKUInventory{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKUInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKUInventory) ProtoMessage() {}

func (x *SKUInventory) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKUInventory.ProtoReflect.Descriptor instead.
func (*SKUInventory) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *SKUInventory) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *SKUInventory) GetCurrentStock() float64 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

func (x *SKUInventory) GetReservedStock() float64 {
	if x != nil {
		return x.ReservedStock
	}
	return 0
}

func (x *SKUInventory) GetMinStockLevel() float64 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *SKUInventory) GetMaxStockLevel() float64 {
	if x != nil {
		return x.MaxStockLevel
	}
	return 0
}

func (x *SKUInventory) GetLastStockUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStockUpdate
	}
	return nil
}

type ReservedSKU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservedSKU) Reset() {
	*x = ReservedSKU{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservedSKU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservedSKU) ProtoMessage() {}

func (x *ReservedSKU) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservedSKU.ProtoReflect.Descriptor instead.
func (*ReservedSKU) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ReservedSKU) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReservedSKU) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReservedSKU) GetReservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservedAt
	}
	return nil
}

type Reserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReserveId     string                 `protobuf:"bytes,2,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	ReservedSkus  []*ReservedSKU         `protobuf:"bytes,3,rep,name=reserved_skus,json=reservedSkus,proto3" json:"reserved_skus,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserve) Reset() {
	*x = Reserve{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserve) ProtoMessage() {}

func (x *Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserve.ProtoReflect.Descriptor instead.
func (*Reserve) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *Reserve) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Reserve) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

func (x *Reserve) GetReservedSkus() []*ReservedSKU {
	if x != nil {
		return x.ReservedSkus
	}
	return nil
}

func (x *Reserve) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reserve) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Requests (unchanged)
type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SkusToReserve []*ReservedSKU         `protobuf:"bytes,2,rep,name=skus_to_reserve,json=skusToReserve,proto3" json:"skus_to_reserve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetSkusToReserve() []*ReservedSKU {
	if x != nil {
		return x.SkusToReserve
	}
	return nil
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReserveId     string                 `protobuf:"bytes,2,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseStockRequest) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{7}
}

func (x *CheckStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CheckStockRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Improved Responses
type CheckStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CheckStockResponse_Success_
	//	*CheckStockResponse_Error
	Result        isCheckStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{8}
}

func (x *CheckStockResponse) GetResult() isCheckStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CheckStockResponse) GetSuccess() *CheckStockResponse_Success {
	if x != nil {
		if x, ok := x.Result.(*CheckStockResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *CheckStockResponse) GetError() *InventoryError {
	if x != nil {
		if x, ok := x.Result.(*CheckStockResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCheckStockResponse_Result interface {
	isCheckStockResponse_Result()
}

type CheckStockResponse_Success_ struct {
	Success *CheckStockResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type CheckStockResponse_Error struct {
	Error *InventoryError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CheckStockResponse_Success_) isCheckStockResponse_Result() {}

func (*CheckStockResponse_Error) isCheckStockResponse_Result() {}

type ReserveStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReserveStockResponse_Success
	//	*ReserveStockResponse_Error
	Result        isReserveStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveStockResponse) GetResult() isReserveStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReserveStockResponse) GetSuccess() *ReserveStockResponse_ReserveSuccess {
	if x != nil {
		if x, ok := x.Result.(*ReserveStockResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ReserveStockResponse) GetError() *InventoryError {
	if x != nil {
		if x, ok := x.Result.(*ReserveStockResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isReserveStockResponse_Result interface {
	isReserveStockResponse_Result()
}

type ReserveStockResponse_Success struct {
	Success *ReserveStockResponse_ReserveSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ReserveStockResponse_Error struct {
	Error *InventoryError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ReserveStockResponse_Success) isReserveStockResponse_Result() {}

func (*ReserveStockResponse_Error) isReserveStockResponse_Result() {}

type ReleaseStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReleaseStockResponse_Success
	//	*ReleaseStockResponse_Error
	Result        isReleaseStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseStockResponse) GetResult() isReleaseStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReleaseStockResponse) GetSuccess() *ReleaseStockResponse_ReleaseSuccess {
	if x != nil {
		if x, ok := x.Result.(*ReleaseStockResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ReleaseStockResponse) GetError() *InventoryError {
	if x != nil {
		if x, ok := x.Result.(*ReleaseStockResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isReleaseStockResponse_Result interface {
	isReleaseStockResponse_Result()
}

type ReleaseStockResponse_Success struct {
	Success *ReleaseStockResponse_ReleaseSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ReleaseStockResponse_Error struct {
	Error *InventoryError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ReleaseStockResponse_Success) isReleaseStockResponse_Result() {}

func (*ReleaseStockResponse_Error) isReleaseStockResponse_Result() {}

type CheckStockResponse_Success struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable       bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	AvailableQuantity float64                `protobuf:"fixed64,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Inventory         *SKUInventory          `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckStockResponse_Success) Reset() {
	*x = CheckStockResponse_Success{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse_Success) ProtoMessage() {}

func (x *CheckStockResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse_Success.ProtoReflect.Descriptor instead.
func (*CheckStockResponse_Success) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CheckStockResponse_Success) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckStockResponse_Success) GetAvailableQuantity() float64 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *CheckStockResponse_Success) GetInventory() *SKUInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type ReserveStockResponse_ReserveSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserve       *Reserve               `protobuf:"bytes,1,opt,name=reserve,proto3" json:"reserve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse_ReserveSuccess) Reset() {
	*x = ReserveStockResponse_ReserveSuccess{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse_ReserveSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse_ReserveSuccess) ProtoMessage() {}

func (x *ReserveStockResponse_ReserveSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse_ReserveSuccess.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse_ReserveSuccess) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ReserveStockResponse_ReserveSuccess) GetReserve() *Reserve {
	if x != nil {
		return x.Reserve
	}
	return nil
}

type ReleaseStockResponse_ReleaseSuccess struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reserve            *Reserve               `protobuf:"bytes,1,opt,name=reserve,proto3" json:"reserve,omitempty"`
	UpdatedInventories []*SKUInventory        `protobuf:"bytes,2,rep,name=updated_inventories,json=updatedInventories,proto3" json:"updated_inventories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReleaseStockResponse_ReleaseSuccess) Reset() {
	*x = ReleaseStockResponse_ReleaseSuccess{}
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse_ReleaseSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse_ReleaseSuccess) ProtoMessage() {}

func (x *ReleaseStockResponse_ReleaseSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_inventory_v1_stock_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse_ReleaseSuccess.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse_ReleaseSuccess) Descriptor() ([]byte, []int) {
	return file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ReleaseStockResponse_ReleaseSuccess) GetReserve() *Reserve {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *ReleaseStockResponse_ReleaseSuccess) GetUpdatedInventories() []*SKUInventory {
	if x != nil {
		return x.UpdatedInventories
	}
	return nil
}

var File_pb_schemas_inventory_v1_stock_proto protoreflect.FileDescriptor

const file_pb_schemas_inventory_v1_stock_proto_rawDesc = "" +
	"\n" +
	"#pb_schemas/inventory/v1/stock.proto\x12\x17pb_schemas.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\"E\n" +
	"\vErrorDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x90\x01\n" +
	"\x0eInventoryError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12>\n" +
	"\adetails\x18\x02 \x03(\v2$.pb_schemas.inventory.v1.ErrorDetailR\adetails\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\"\x84\x02\n" +
	"\fSKUInventory\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12#\n" +
	"\rcurrent_stock\x18\x02 \x01(\x01R\fcurrentStock\x12%\n" +
	"\x0ereserved_stock\x18\x03 \x01(\x01R\rreservedStock\x12&\n" +
	"\x0fmin_stock_level\x18\x04 \x01(\x01R\rminStockLevel\x12&\n" +
	"\x0fmax_stock_level\x18\x05 \x01(\x01R\rmaxStockLevel\x12F\n" +
	"\x11last_stock_update\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastStockUpdate\"x\n" +
	"\vReservedSKU\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12;\n" +
	"\vreserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reservedAt\"\xe1\x01\n" +
	"\aReserve\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x02 \x01(\tR\treserveId\x12I\n" +
	"\rreserved_skus\x18\x03 \x03(\v2$.pb_schemas.inventory.v1.ReservedSKUR\freservedSkus\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"~\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12L\n" +
	"\x0fskus_to_reserve\x18\x02 \x03(\v2$.pb_schemas.inventory.v1.ReservedSKUR\rskusToReserve\"O\n" +
	"\x13ReleaseStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x02 \x01(\tR\treserveId\"A\n" +
	"\x11CheckStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\xd3\x02\n" +
	"\x12CheckStockResponse\x12O\n" +
	"\asuccess\x18\x01 \x01(\v23.pb_schemas.inventory.v1.CheckStockResponse.SuccessH\x00R\asuccess\x12?\n" +
	"\x05error\x18\x02 \x01(\v2'.pb_schemas.inventory.v1.InventoryErrorH\x00R\x05error\x1a\xa0\x01\n" +
	"\aSuccess\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x01R\x11availableQuantity\x12C\n" +
	"\tinventory\x18\x03 \x01(\v2%.pb_schemas.inventory.v1.SKUInventoryR\tinventoryB\b\n" +
	"\x06result\"\x89\x02\n" +
	"\x14ReserveStockResponse\x12X\n" +
	"\asuccess\x18\x01 \x01(\v2<.pb_schemas.inventory.v1.ReserveStockResponse.ReserveSuccessH\x00R\asuccess\x12?\n" +
	"\x05error\x18\x02 \x01(\v2'.pb_schemas.inventory.v1.InventoryErrorH\x00R\x05error\x1aL\n" +
	"\x0eReserveSuccess\x12:\n" +
	"\areserve\x18\x01 \x01(\v2 .pb_schemas.inventory.v1.ReserveR\areserveB\b\n" +
	"\x06result\"\xe2\x02\n" +
	"\x14ReleaseStockResponse\x12X\n" +
	"\asuccess\x18\x01 \x01(\v2<.pb_schemas.inventory.v1.ReleaseStockResponse.ReleaseSuccessH\x00R\asuccess\x12?\n" +
	"\x05error\x18\x02 \x01(\v2'.pb_schemas.inventory.v1.InventoryErrorH\x00R\x05error\x1a\xa4\x01\n" +
	"\x0eReleaseSuccess\x12:\n" +
	"\areserve\x18\x01 \x01(\v2 .pb_schemas.inventory.v1.ReserveR\areserve\x12V\n" +
	"\x13updated_inventories\x18\x02 \x03(\v2%.pb_schemas.inventory.v1.SKUInventoryR\x12updatedInventoriesB\b\n" +
	"\x06result2\xd3\x02\n" +
	"\x10InventoryService\x12e\n" +
	"\n" +
	"CheckStock\x12*.pb_schemas.inventory.v1.CheckStockRequest\x1a+.pb_schemas.inventory.v1.CheckStockResponse\x12k\n" +
	"\fReserveStock\x12,.pb_schemas.inventory.v1.ReserveStockRequest\x1a-.pb_schemas.inventory.v1.ReserveStockResponse\x12k\n" +
	"\fReleaseStock\x12,.pb_schemas.inventory.v1.ReleaseStockRequest\x1a-.pb_schemas.inventory.v1.ReleaseStockResponseB3Z1ops-monorepo/protogen/go/inventory/v1;inventoryv1b\x06proto3"

var (
	file_pb_schemas_inventory_v1_stock_proto_rawDescOnce sync.Once
	file_pb_schemas_inventory_v1_stock_proto_rawDescData []byte
)

func file_pb_schemas_inventory_v1_stock_proto_rawDescGZIP() []byte {
	file_pb_schemas_inventory_v1_stock_proto_rawDescOnce.Do(func() {
		file_pb_schemas_inventory_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_schemas_inventory_v1_stock_proto_rawDesc), len(file_pb_schemas_inventory_v1_stock_proto_rawDesc)))
	})
	return file_pb_schemas_inventory_v1_stock_proto_rawDescData
}

var file_pb_schemas_inventory_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_schemas_inventory_v1_stock_proto_goTypes = []any{
	(*ErrorDetail)(nil),                         // 0: pb_schemas.inventory.v1.ErrorDetail
	(*InventoryError)(nil),                      // 1: pb_schemas.inventory.v1.InventoryError
	(*SKUInventory)(nil),                        // 2: pb_schemas.inventory.v1.SKUInventory
	(*ReservedSKU)(nil),                         // 3: pb_schemas.inventory.v1.ReservedSKU
	(*Reserve)(nil),                             // 4: pb_schemas.inventory.v1.Reserve
	(*ReserveStockRequest)(nil),                 // 5: pb_schemas.inventory.v1.ReserveStockRequest
	(*ReleaseStockRequest)(nil),                 // 6: pb_schemas.inventory.v1.ReleaseStockRequest
	(*CheckStockRequest)(nil),                   // 7: pb_schemas.inventory.v1.CheckStockRequest
	(*CheckStockResponse)(nil),                  // 8: pb_schemas.inventory.v1.CheckStockResponse
	(*ReserveStockResponse)(nil),                // 9: pb_schemas.inventory.v1.ReserveStockResponse
	(*ReleaseStockResponse)(nil),                // 10: pb_schemas.inventory.v1.ReleaseStockResponse
	(*CheckStockResponse_Success)(nil),          // 11: pb_schemas.inventory.v1.CheckStockResponse.Success
	(*ReserveStockResponse_ReserveSuccess)(nil), // 12: pb_schemas.inventory.v1.ReserveStockResponse.ReserveSuccess
	(*ReleaseStockResponse_ReleaseSuccess)(nil), // 13: pb_schemas.inventory.v1.ReleaseStockResponse.ReleaseSuccess
	(*status.Status)(nil),                       // 14: google.rpc.Status
	(*timestamppb.Timestamp)(nil),               // 15: google.protobuf.Timestamp
}
var file_pb_schemas_inventory_v1_stock_proto_depIdxs = []int32{
	0,  // 0: pb_schemas.inventory.v1.InventoryError.details:type_name -> pb_schemas.inventory.v1.ErrorDetail
	14, // 1: pb_schemas.inventory.v1.InventoryError.status:type_name -> google.rpc.Status
	15, // 2: pb_schemas.inventory.v1.SKUInventory.last_stock_update:type_name -> google.protobuf.Timestamp
	15, // 3: pb_schemas.inventory.v1.ReservedSKU.reserved_at:type_name -> google.protobuf.Timestamp
	3,  // 4: pb_schemas.inventory.v1.Reserve.reserved_skus:type_name -> pb_schemas.inventory.v1.ReservedSKU
	15, // 5: pb_schemas.inventory.v1.Reserve.created_at:type_name -> google.protobuf.Timestamp
	3,  // 6: pb_schemas.inventory.v1.ReserveStockRequest.skus_to_reserve:type_name -> pb_schemas.inventory.v1.ReservedSKU
	11, // 7: pb_schemas.inventory.v1.CheckStockResponse.success:type_name -> pb_schemas.inventory.v1.CheckStockResponse.Success
	1,  // 8: pb_schemas.inventory.v1.CheckStockResponse.error:type_name -> pb_schemas.inventory.v1.InventoryError
	12, // 9: pb_schemas.inventory.v1.ReserveStockResponse.success:type_name -> pb_schemas.inventory.v1.ReserveStockResponse.ReserveSuccess
	1,  // 10: pb_schemas.inventory.v1.ReserveStockResponse.error:type_name -> pb_schemas.inventory.v1.InventoryError
	13, // 11: pb_schemas.inventory.v1.ReleaseStockResponse.success:type_name -> pb_schemas.inventory.v1.ReleaseStockResponse.ReleaseSuccess
	1,  // 12: pb_schemas.inventory.v1.ReleaseStockResponse.error:type_name -> pb_schemas.inventory.v1.InventoryError
	2,  // 13: pb_schemas.inventory.v1.CheckStockResponse.Success.inventory:type_name -> pb_schemas.inventory.v1.SKUInventory
	4,  // 14: pb_schemas.inventory.v1.ReserveStockResponse.ReserveSuccess.reserve:type_name -> pb_schemas.inventory.v1.Reserve
	4,  // 15: pb_schemas.inventory.v1.ReleaseStockResponse.ReleaseSuccess.reserve:type_name -> pb_schemas.inventory.v1.Reserve
	2,  // 16: pb_schemas.inventory.v1.ReleaseStockResponse.ReleaseSuccess.updated_inventories:type_name -> pb_schemas.inventory.v1.SKUInventory
	7,  // 17: pb_schemas.inventory.v1.InventoryService.CheckStock:input_type -> pb_schemas.inventory.v1.CheckStockRequest
	5,  // 18: pb_schemas.inventory.v1.InventoryService.ReserveStock:input_type -> pb_schemas.inventory.v1.ReserveStockRequest
	6,  // 19: pb_schemas.inventory.v1.InventoryService.ReleaseStock:input_type -> pb_schemas.inventory.v1.ReleaseStockRequest
	8,  // 20: pb_schemas.inventory.v1.InventoryService.CheckStock:output_type -> pb_schemas.inventory.v1.CheckStockResponse
	9,  // 21: pb_schemas.inventory.v1.InventoryService.ReserveStock:output_type -> pb_schemas.inventory.v1.ReserveStockResponse
	10, // 22: pb_schemas.inventory.v1.InventoryService.ReleaseStock:output_type -> pb_schemas.inventory.v1.ReleaseStockResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pb_schemas_inventory_v1_stock_proto_init() }
func file_pb_schemas_inventory_v1_stock_proto_init() {
	if File_pb_schemas_inventory_v1_stock_proto != nil {
		return
	}
	file_pb_schemas_inventory_v1_stock_proto_msgTypes[8].OneofWrappers = []any{
		(*CheckStockResponse_Success_)(nil),
		(*CheckStockResponse_Error)(nil),
	}
	file_pb_schemas_inventory_v1_stock_proto_msgTypes[9].OneofWrappers = []any{
		(*ReserveStockResponse_Success)(nil),
		(*ReserveStockResponse_Error)(nil),
	}
	file_pb_schemas_inventory_v1_stock_proto_msgTypes[10].OneofWrappers = []any{
		(*ReleaseStockResponse_Success)(nil),
		(*ReleaseStockResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_schemas_inventory_v1_stock_proto_rawDesc), len(file_pb_schemas_inventory_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_schemas_inventory_v1_stock_proto_goTypes,
		DependencyIndexes: file_pb_schemas_inventory_v1_stock_proto_depIdxs,
		MessageInfos:      file_pb_schemas_inventory_v1_stock_proto_msgTypes,
	}.Build()
	File_pb_schemas_inventory_v1_stock_proto = out.File
	file_pb_schemas_inventory_v1_stock_proto_goTypes = nil
	file_pb_schemas_inventory_v1_stock_proto_depIdxs = nil
}
