// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

// AnyValue defines model for AnyValue.
type AnyValue = interface{}

// BaseSuccessResponse defines model for BaseSuccessResponse.
type BaseSuccessResponse struct {
	Data       *AnyValue `json:"data,omitempty"`
	Message    string    `json:"message"`
	StatusCode int       `json:"status_code"`
}

// CreateOrderSuccessResponse defines model for CreateOrderSuccessResponse.
type CreateOrderSuccessResponse struct {
	Data       AnyValue `json:"data"`
	Message    string   `json:"message"`
	StatusCode int      `json:"status_code"`
}

// OrderRequest defines model for OrderRequest.
type OrderRequest struct {
	OrderItems []StockItemRequest `json:"order_items"`
}

// OutOfStockItemResp defines model for OutOfStockItemResp.
type OutOfStockItemResp struct {
	AvailableQuantity *string `json:"available_quantity,omitempty"`
	ProductId         *string `json:"product_id,omitempty"`
	ProductName       *string `json:"product_name,omitempty"`
	RequestedQuantity *string `json:"requested_quantity,omitempty"`
	Sku               *string `json:"sku,omitempty"`
}

// OutOfStockItems defines model for OutOfStockItems.
type OutOfStockItems struct {
	OutOfStockItems *[]OutOfStockItemResp `json:"out_of_stock_items,omitempty"`
}

// OutofStockResponse defines model for OutofStockResponse.
type OutofStockResponse struct {
	Details          *OutOfStockItems `json:"details,omitempty"`
	Message          *string          `json:"message,omitempty"`
	StatusCode       *int             `json:"status_code,omitempty"`
	SuggestedActions *[]string        `json:"suggested_actions,omitempty"`
}

// StandardErrorResponse defines model for StandardErrorResponse.
type StandardErrorResponse struct {
	Details   *string                 `json:"details,omitempty"`
	Errors    *map[string]interface{} `json:"errors,omitempty"`
	Instance  *string                 `json:"instance,omitempty"`
	Status    *int                    `json:"status,omitempty"`
	Timestamp *string                 `json:"timestamp,omitempty"`
	Title     *string                 `json:"title,omitempty"`
	TraceId   *string                 `json:"trace_id,omitempty"`
	Type      *string                 `json:"type,omitempty"`
}

// StockItemRequest defines model for StockItemRequest.
type StockItemRequest struct {
	QuantityPerUom float64 `json:"quantity_per_uom" validate:"required,gt=0"`
	Sku            string  `json:"sku" validate:"required,unique"`
	Uom            string  `json:"uom" validate:"required"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = OrderRequest
