// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pb_schemas/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Email request message
type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	IsHtml        bool                   `protobuf:"varint,5,opt,name=is_html,json=isHtml,proto3" json:"is_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_pb_schemas_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_pb_schemas_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailRequest) GetIsHtml() bool {
	if x != nil {
		return x.IsHtml
	}
	return false
}

// Email response message
type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EmailId       string                 `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_pb_schemas_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_schemas_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_pb_schemas_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailResponse) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *SendEmailResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pb_schemas_notification_v1_notification_proto protoreflect.FileDescriptor

const file_pb_schemas_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"-pb_schemas/notification/v1/notification.proto\x12\x1apb_schemas.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x17\n" +
	"\ais_html\x18\x05 \x01(\bR\x06isHtml\"\x9c\x01\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bemail_id\x18\x03 \x01(\tR\aemailId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x81\x01\n" +
	"\x13NotificationService\x12j\n" +
	"\tSendEmail\x12,.pb_schemas.notification.v1.SendEmailRequest\x1a-.pb_schemas.notification.v1.SendEmailResponse\"\x00B9Z7ops-monorepo/protogen/go/notification/v1;notificationv1b\x06proto3"

var (
	file_pb_schemas_notification_v1_notification_proto_rawDescOnce sync.Once
	file_pb_schemas_notification_v1_notification_proto_rawDescData []byte
)

func file_pb_schemas_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_pb_schemas_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_pb_schemas_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_schemas_notification_v1_notification_proto_rawDesc), len(file_pb_schemas_notification_v1_notification_proto_rawDesc)))
	})
	return file_pb_schemas_notification_v1_notification_proto_rawDescData
}

var file_pb_schemas_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_schemas_notification_v1_notification_proto_goTypes = []any{
	(*SendEmailRequest)(nil),      // 0: pb_schemas.notification.v1.SendEmailRequest
	(*SendEmailResponse)(nil),     // 1: pb_schemas.notification.v1.SendEmailResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pb_schemas_notification_v1_notification_proto_depIdxs = []int32{
	2, // 0: pb_schemas.notification.v1.SendEmailResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: pb_schemas.notification.v1.NotificationService.SendEmail:input_type -> pb_schemas.notification.v1.SendEmailRequest
	1, // 2: pb_schemas.notification.v1.NotificationService.SendEmail:output_type -> pb_schemas.notification.v1.SendEmailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_schemas_notification_v1_notification_proto_init() }
func file_pb_schemas_notification_v1_notification_proto_init() {
	if File_pb_schemas_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_schemas_notification_v1_notification_proto_rawDesc), len(file_pb_schemas_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_schemas_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_pb_schemas_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_pb_schemas_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_pb_schemas_notification_v1_notification_proto = out.File
	file_pb_schemas_notification_v1_notification_proto_goTypes = nil
	file_pb_schemas_notification_v1_notification_proto_depIdxs = nil
}
