// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIOrder creates a new instance of MockIOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrder {
	mock := &MockIOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIOrder is an autogenerated mock type for the IOrder type
type MockIOrder struct {
	mock.Mock
}

type MockIOrder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrder) EXPECT() *MockIOrder_Expecter {
	return &MockIOrder_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockIOrder
func (_mock *MockIOrder) CreateOrder(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIOrder_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockIOrder_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIOrder_Expecter) CreateOrder(c interface{}) *MockIOrder_CreateOrder_Call {
	return &MockIOrder_CreateOrder_Call{Call: _e.mock.On("CreateOrder", c)}
}

func (_c *MockIOrder_CreateOrder_Call) Run(run func(c *gin.Context)) *MockIOrder_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIOrder_CreateOrder_Call) Return() *MockIOrder_CreateOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIOrder_CreateOrder_Call) RunAndReturn(run func(c *gin.Context)) *MockIOrder_CreateOrder_Call {
	_c.Run(run)
	return _c
}
